# Analysing Natural Disasters since 1900
Maxwell Arena, Nathan Poteet, Sanjay, Akshay
# Outline
// finish this later

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import f
import seaborn as sns
from sklearn import model_selection
from sklearn import linear_model
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
import statsmodels.formula.api as smf
import requests

In [22]:
# https://cmsc320.github.io/files/cmsc320_f2021_final_rubric.pdf

In [ ]:
https://www.kaggle.com/mathurinache/natural-disasters-data-explorer

In [23]:
from google.colab import drive
drive.mount('/content/drive')
root_dir = "/content/drive/My Drive/"
path = root_dir + 'Colab Notebooks/320Final/natural-disasters.csv'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [24]:
data = pd.read_csv(path)
data

      Number of deaths from drought  ...  total_affected_rate_per_100k_all_disasters
0                               0.0  ...                                    2.381236
1                               0.0  ...                                   44.060951
2                               0.0  ...                                  547.029875
3                               0.0  ...                                  218.081859
4                               0.0  ...                                  316.150814
...                             ...  ...                                         ...
1599                            0.0  ...                                    0.000000
1600                            0.0  ...                                    0.000000
1601                            0.0  ...                                 4839.765250
1602                            0.0  ...                                 7023.254487
1603                            0.0  ...                                 9656.191875

[1604 rows x 171 columns]